### PR TITLE
Add worksheet04 to notes

### PR DESCRIPTION
**Pull request by risheetnair**
The Pull Request `for completing worksheet 4`

### CODE REVIEW

**Review by gallettilance — CHANGES_REQUESTED** [review]
nice work on worksheet 4! can you please remove the changes made to lab02 and the initial notes.txt so that I can merge this?

**Comment by risheetnair** [comment]
did that work? I'm still not 100% sure with Git

**Review by gallettilance — CHANGES_REQUESTED** [review]
the .txt file was successfully removed but the lab changes are still there

**Comment by risheetnair** [comment]
How about now? If not, I'll come to office hours next week to get it figured out.

**Review by gallettilance — APPROVED** [review]
nicely done!!

**Pull request merged**
